---
- hosts: 172.31.8.212
  become: yes 
  tasks: 
  - include_tasks: myfile.yml
  - name : static file into ansible nodes
    copy: 
       src: mytestfile 
       dest: /home/ubuntu/mystaticfile
  - name: install webserver
    apt: 
       name: apache2 
       state: present 
  - name: copy  dynamic files into ansible nodes 
    template: 
         src: myindex.j2 
         dest: /var/www/html/index.html

  - name: download internet fles into nodes
    get_url:
      url: https://get.jenkins.io/war-stable/2.346.2/jenkins.war
      dest: /etc/jenkins.war
      force_basic_auth: yes 





