---
- hosts: 172.31.8.212
  become: yes 
  tasks: 
  - include_tasks: myfile.yml
  - name : sattic file into ansible nodes
    copy: 
       src: mytestfile 
       dest: /home/ubuntu/mysatticfile



