---
- hosts: 172.31.8.212
  become: yes 
  tasks: 
  - include_tasks: myfile.yml
  - name: copy sattic files into ansible nodes 
    copy: 
       src: mytestfile  
       dest: /home/ubuntu/mysatticfile
  - name: install webserver 
    apt: 
       name: apache2 
       state: present    



  


