---
- hosts: all
  become: yes
  tasks:
  - name: install git 
    apt: 
       name: git 
       state: present 
  - name: install wget
    apt:
       name: 
       state: present 
  - name: install tree 
    apt: 
       name: tree
       state: present
