---
- hosts: 172.31.11.50
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy static files ansible nodes
    copy: 
       src: mytestfile
       dest: /home/ubuntu/mysaticfile

    

