---
- hosts: 172.31.11.50
  become: yes 
  tasks:
  - include_tasks: myfile.yml
  - name : copy sattic file into ansible nodes 
    copy: 
        src: mytestfile
        dest: /home/ubuntu/mysatticfile
  - name: install webserver
    apt: 
       name: apache2 
       state: present

  - name: copy dynamic files into ansible nodes
    templates:
          src: myindex.j2
          dest: /var/index/html/index.html            
