---
- hosts: mywebservers
  become: yes 
  tasks: 
  - name: install java on ubuntu ansible nodes 
    apt: 
       name: "{{myjavapackonubuntu}}"
       state: present 
    when: ansible_os_family =="Debian"

  - name: install javaon on redhat ansible nodes
    yum: 
       name: "{{myjavapackonredhat}}"
       state: present 
    when: ansible_os_family =="RedHat"     
