---
- hosts: 172.31.8.212
  become: yes 
  tasks: 
  - name: install git 
    apt: 
       name: git 
       state: present 
    mytags: git 

  - name: install tree 
    apt: 
       name: tree 
       state: present
    mytags: tree     

  - name: install wget 
    apt: 
       name: wget 
       state: present
    mytags: wget                