---
- hosts: 172.31.8.212
  become: yes 
  tasks: 

- name: git 
  apt: 
     name: git 
     state: present 


- name: install tree 
  apt: 
     name: tree 
     state: present 

- name: install wget 
  apt: 
     name: wget 
     state: present             
