---
- hosts: mywebservers
  become: yes 
  tasks: 
  - name: install webserver on ubuntu ansible nodes
    apt: 
       name: "{{mywebserverspackonubuntu}}" 
       state: present
    when: ansible_os_family== "Debian"    

  - name: start webserver on ubuntu ansible nodes 
    service: 
         name: "{{mywebserverspackonubuntu}}"
         state: started
    when: ansible_os_family== "Debian"

  - name: install webserver on RedHat ansible nodes
    yum: 
       name: "{{mywebserverspackonredhat}}" 
       state: present
    when: ansible_os_family =="RedHat"

  - name: star webserver on RedHat ansible nodes
    service: 
        name: "{{mywebserverspackonredhat}}"
        state: started 
    when: ansible_os_family =="RedHat"





