---
- hosts: all 
  become: yes 
  tasks: 
  - name: install webserver ubuntu on ansible nodes
    apt: 
       name: apache2 
       state: present
    when: ansible_os_family== "Debian"   

  - name: start webserver on ubuntu ansible nodes
    service: 
        name: apache2 
        state: started
    when: ansible_os_family== "Debian"    

  - name: install webserver on RedHat ansible nodes
    yum: 
      name: httpd
      state: present
    when: ansible_os_family =="RedHat"

  - name: start webserver on RedHat on ansible nodes
    service: 
        name: httpd
        state: started
    when: ansible_os_family =="RedHat"    

      
        