---
- hosts: all 
  become: yes
  tasks: 
  - name: install webserver ubuntu on ansible nodes
    apt: 
       name: apache2
       state: present 

  - name: start webserver on ubuntu ansible nodes
    service: 
       name: apache2
       state: started 
